### PR TITLE
adding user realm role assignment to user resource

### PR DESCRIPTION
**Pull request by becjon**
Hey, Thank you for this keycloak provider. I missed the feature to assign realm roles to user and implemented it. It would be great if you could review the PR and Merge it

I found the following issue that also references this desire.
https://github.com/mrparkers/terraform-provider-keycloak/issues/152

### CODE REVIEW

**Comment by mrparkers** [comment]
Hi @becjon, thanks for the PR!

Did you have any thoughts around the example HCL I posted in #152 to solve this problem, specifically the `keycloak_user_roles` resource?  I liked that approach because it would allow you to map roles to Keycloak users that were federated from external sources, such as an LDAP directory.  I think that would cover more use cases than using the `keycloak_user` resource for this, since it will allow you to assign roles to users regardless of how they were created.

What are your thoughts on this?

**Comment by becjon** [comment]
Hi @mrparkers, yes you are right. An implementation in an own resource has more use-cases. Your example looks good to me. I think the state management for assigned roles would also be easier to handle in an own resource.

**Comment by mrparkers** [comment]
Would you be okay with updating your implementation so that its moved to its own resource?  I think most of the code in the `keycloak` package will remain the same.  Let me know your thoughts on this.

**Comment by mrparkers** [comment]
This functionality has been implemented in #315

**Pull request closed without merging**
