### PR TITLE
fix for user attribute value with length bigger than 255 symbols

### PR DESCRIPTION
**Pull request by AndrewChubatiuk**
Hello again, @mrparkers
Prepared a small PR for a case when user attribute value is bigger than 255 symbols.
Keycloak web automatically splits too long strings into a slice with a string length up to 255 symbols.
My PR does the same

### CODE REVIEW

**Comment by AndrewChubatiuk** [comment]
PR is ready, but build is failing from time to time

**Comment by mrparkers** [comment]
Thanks for the PR, would you be able to add a test for the scenario you're fixing?

**Comment by AndrewChubatiuk** [comment]
Yep. Just added

**Comment by AndrewChubatiuk** [comment]
@mrparkers Yep. Just added

**Comment by AndrewChubatiuk** [comment]
@tomrutsaert 
What platform do you use?

**Comment by tomrutsaert** [comment]
Ubuntu 18.04.2 LTS

**Pull request merged**
