### PR TITLE
Add Management Permissions, Sync Mode and generic client role mapper.

### PR DESCRIPTION
**Pull request by m-v-k**
- keycloak_generic_client_role_mapper
- Partial support for Management Permissions
- Identity Brokering Sync Mode (Keycloak 10)

### Extension of existing keycloak_generic_client_role_mapper resource used to generically associate roles to client/client-scope with ability to include realm-level roles association.

usage example:
```
resource "keycloak_role" "realm_admin" {
  realm_id    = "[example_realm]"
  name        = "realm_admin"
  description = "Admin realm role"
}

resource "keycloak_openid_client_scope" "petstore_api_access_scope" {
  realm_id        = "[example_realm]"
  name            = "petstore-api-access"
  description     = "scope offering additional information for petstore api access"
}

resource "keycloak_generic_client_role_mapper" "petstore_api_access_scope_admin" {
    realm_id           = "[example_realm]"
    client_scope_id    = keycloak_openid_client_scope.petstore_api_access_scope.id
    role_id            = keycloak_role.realm_admin.id
}
```

### Partial implementation of the issue Support Management Permissions Reference [#285](https://github.com/mrparkers/terraform-provider-keycloak/issues/285)

Implemented is the management permissions reference for clients (/{realm}/clients/{id}/management/permissions).
Import example for a client which id is 72e58412-1137-407b-af8b-805e40aa60be:

usage example:
```
resource "keycloak_openid_client_management_permissions_reference" "permissions_reference" {
}
```

terraform import keycloak_openid_client_management_permissions_reference.permissions_reference test_realm/clients/72e58412-1137-407b-af8b-805e40aa60be/management/permissions

Setting on the management permissions reference for a client:
```
resource "keycloak_openid_client_management_permissions_reference" "management_permissions_reference" {
  realm_id        = [realm_id]
  client_id       = [client_id]
}
```

### KC10 introduced Identity Brokering Sync Mode with mandatory 'Sync Mode Override' field in all IDP mappers. 
This is the extension of the provider to support this in the form of an added "extra_config" optional field which can take any values and maps them in IDP Mappers Configuration.

usage example (against KC10):
```
resource keycloak_oidc_identity_provider oidc {
    realm                = "my-realm"
    alias                = "my-idp"
    authorization_url    = "https://authorizationurl.com"
    client_id            = "clientID"
    client_secret        = "clientSecret" # or "$${vault.ID}"
    token_url            = "https://tokenurl.com"
    extra_config         = {
      "clientAuthMethod"    = "client_secret_post"
    }
}

resource keycloak_hardcoded_role_identity_provider_mapper oidc {
    realm                   = "[realm]"
    name                    = "[hardcodedRole]"
    identity_provider_alias = keycloak_oidc_identity_provider.oidc.alias
    role                    = "[role]"
    extra_config            = {
        syncMode = "FORCE"
    }
}
```

also includes examples and tests.

### CODE REVIEW

**Comment by m-v-k** [comment]
(@mrparkers , please rerun that timed out test)

**Comment by mrparkers** [comment]
Nice changes here, thanks @m-v-k, @slavko-vega, and @branislav-vega!

This is a pretty large PR so I'll take some time over the weekend to look it over.

**Comment by m-v-k** [comment]
hey @mrparkers , any update on this pr?
just fyi, we currently use this version in (10.0.2) production environment without pain. but i would prefer upstreaming and consuming the community version.  just wondering when to expect a merge or feedback.
we are happy to help if necessary.
thanks

**Comment by mrparkers** [comment]
@m-v-k I'm sorry, I've neglected this PR.  I know I said this last time, but I've legitimately set aside time this weekend to take care of the open PRs on this project (including this one) as well as a few of the issues.

I appreciate your patience and the contribution you've made here.  Hopefully we'll be able to include these changes in a release some time next week.

**Comment by m-v-k** [comment]
Thanks @mrparkers , 
I agree, i think it's best to drop that `keycloak_openid_client_management_permissions_reference` resource for now, look at the 2 comments and merge the rest. We'll have a look this week.

**Comment by tomrutsaert** [comment]
My 2 cents concerning the permission part.

Idp configuration also has a "Permission" tab. I created support for it in #318. (it is still a preview feature, but it is the same is this)
This biggest difference is that I only needed take into account the token exchange scope based permission. For the openid client, enabling the permissions, automatically creates 8 scope based permissions.
image
Generally once an administrator enables the permission on a client, he only needs to a specific policy on 1 or more  permissions and he is done.
The point is, enabling permissions on a openid client creates a whole bunch of things under the hood on the fine grained authorization services of the 'realm-management client. It is not just a simple switch that is on or off.

So imho just like I did in #318, I think is good idea to handle it as a separate resource.
I do not know If automatically creating a policy in this case would be good idea. (which I did)
I do not even know if it was good idea within #318.

**Comment by slavko-vega** [comment]
Thank you @mrparkers and @tomrutsaert. As @m-v-k wrote, we're dropping keycloak_openid_client_management_permissions_reference from this PR. We also made changes on code accordingly to @mrparkers comments and the upstream branch is updated. @mrparkers, could you review the PR now?

**Pull request merged**
