### PR TITLE
Add openid_user_client_role_mapper

### PR DESCRIPTION
**Pull request by dlechevalier**

### CODE REVIEW

**Comment by amfl** [comment]
Looks like this aims to resolve #228

**Comment by mrparkers** [comment]
Hey @dlechevalier, thanks for the PR!  Can you run `make fmt` and push those changes?  This will allow CI to continue with running the tests.

**Comment by dlechevalier** [comment]
Yes @mrparkers , WIP ;)

**Comment by mrparkers** [comment]
My apologies, I didn't realize this was a work in progress.  Feel free to let me know when you're ready for a review.

**Comment by dlechevalier** [comment]
Don't apologize @mrparkers , i didn't mentioned it was in progress ;)
Thanks for the tip. It passed the CI, we can have a review now.

**Comment by mrparkers** [comment]
The code LGTM, nice work!

The only thing I wanted to comment on was the `client_client_id` attribute.  I'm worried that the name might be confusing, since we already have to set a `client_id` in order to tie this mapper to a client.

What do you think about something like `client_id_for_role_mappings`?  It's a bit verbose but I think it makes it easier to understand what the attribute is used for.

Let me know what you think.  Thanks!

**Comment by dlechevalier** [comment]
You're right for client_client_id, it sounds a bit confusing. Ok for client_id_for_role_mappings.
I update , rebase and push this change today (it's 9.30 AM in my place).
Thanks for your advices!

**Comment by dlechevalier** [comment]
@mrparkers i changed client_client_id to client_id_for_role_mappings but add some ugly commits and can't rebase properly. Do you want me to cancel PR and clean my branch?

**Pull request closed without merging**
