### PR TITLE
Add field session_note to user session protocol mapper. This field ne…

### PR DESCRIPTION
**Pull request by hcl31415**
Add field session_note to user session protocol mapper. This field needs to be written additionally to session_note_label if the protocol mapper is intended to work correctly, e.g. an Apache mod_auth_openidc client.

### CODE REVIEW

**Comment by mrparkers** [comment]
Huh, I swear this attribute in the protocol mapper used to be called "session note label", but it appears to have disappeared completely from the UI.  I think it might have been silently renamed in one of the releases since I originally created this resource.

What do you think about simply renaming the existing `session_note_label` attribute to `session_note`?  If you're fine with this, I can push the change to your branch, or you could take a stab at it.

**Comment by hcl31415** [comment]
That's perfectly fine with me. I just kept the original session note label field because I didn't want to introduce unintended behaviour in Keycloak. It seems though that the value of the session note label is still stored in the database, when PUT or POST against the admin API but in the end I couldn't find out what it really does.

**Comment by hcl31415** [comment]
I removed the session-note-label field from the commit.

**Review by mrparkers — APPROVED** [review]
LGTM :+1:

**Pull request merged**
