### PR TITLE
Update license for project to Apache 2.0

### PR DESCRIPTION
**Pull request by mrparkers**
This PR changes the license of the Keycloak Terraform Provider to Apache 2.0. This is necessary for taking over the Keycloak Terraform Provider as part of the Keycloak CNCF project since Apache 2.0 is the standard license for CNCF project.

In order to change the license, we need approvals from all people who contributed to the Keycloak Terraform Provider on this PR. We will reach out to all contributors in the coming days to get their approval.

### CODE REVIEW

**Review by kherock — APPROVED** [review]

**Review by thomasdarimont — APPROVED** [review]

**Comment by sschu** [comment]
To share a bit more context:

Michael has done an outstanding job with the provider, and thanks to the contributions from many people, it has become widely adopted, as highlighted in [our recent survey](https://www.keycloak.org/2024/09/realm-config-management-tools-survey-results). However, due to changes in his work priorities, Michael no longer has the time to maintain the provider. He has kindly approached the Keycloak maintainers to take over its stewardship, and after careful consideration, we agreed.

To integrate the provider into the Keycloak project, we need to change its license to Apache 2.0, which is the standard license for CNCF projects. We need the consent of all contributors to do this. We kindly ask all contributors to review and approve this PR by clicking on the "Files changed" tab, afterwards the “Review changes” button at the top-right corner and selecting “Approve.”

A big thanks to all the contributors!

**Comment by sschu** [comment]
@f-stibane @joeyberkovitz @spirius @chanhht @pths @olivierboudet @ctrox @PSanetra @daviddelannoy @hawknewton @puzzlermike @dmeyerholt @francois-travais @dnic @aromeyer @Korsarro69 @whiskeysierra @fapian @moritz31 @lathspell @toddkazakov @gansb @sl-benoitoyez @Shubhammathur22 @scheying @jgrgt @jkemming @hcl31415 @paulvollmer @arminfelder @languitar @alevit33 @hamiltont @awilliamsOM1 @alex-hempel @Photonios @ltscif @kherock @randomswdev @guthypeter @pmellati @jjarman-uk @jrpedrianes @diffusedlight @wombat @PaulGgithub @LoicGombeaud @hnnsngl @chifu1234 @smoehrle @pablo-ruth @MatrixCrawler @ChrisHubinger @dwaynebailey @sanderginn @Redestros @SvenHamers @Filirom1 @Xide @naushadh @max-rocket-internet @cthiebault @JackHartley @mohammedalics @bplotnick-humane @imykolenko @svenhartmann @stale-vegait @1337andre @pstanton237 @xiaoyang-connyun @DOboznyi @marwol-fdir @Kent1 @elmarx @aroemers @RomanNess @pascal-hofmann @camelpunch @vhiairrassary @darin-sai

**Review by AdrienFromToulouse — APPROVED** [review]

**Review by toddkazakov — APPROVED** [review]

**Comment by sschu** [comment]
@pablo-ruth @MatrixCrawler @ChrisHubinger @dwaynebailey @sanderginn @Redestros @SvenHamers @Filirom1 @Xide @naushadh @max-rocket-internet @cthiebault @JackHartley @mohammedalics @bplotnick-humane @imykolenko @svenhartmann @stale-vegait @1337andre @pstanton237 @xiaoyang-connyun @DOboznyi @marwol-fdir @Kent1 @elmarx @aroemers @RomanNess @pascal-hofmann @camelpunch @vhiairrassary @darin-sai

**Review by dwaynebailey — APPROVED** [review]

**Review by languitar — APPROVED** [review]

**Review by waldemarschmalz — APPROVED** [review]

**Review by moritz31 — APPROVED** [review]

**Review by marwol-fdir — APPROVED** [review]

**Review by oysteinhauan — APPROVED** [review]
Awesome 🙌🏻🙌🏻 Thanks for all your hard work, @mrparkers

**Review by fapian — APPROVED** [review]

**Review by marcoreni — APPROVED** [review]

**Review by olivierboudet — APPROVED** [review]

**Review by max-rocket-internet — APPROVED** [review]

**Review by mukuru-shaun — APPROVED** [review]

**Review by jrpedrianes — APPROVED** [review]

**Review by camjjack — APPROVED** [review]

**Review by hoeggi — APPROVED** [review]

**Review by joeyberkovitz — APPROVED** [review]

**Review by puzzlermike — APPROVED** [review]

**Review by elmarx — APPROVED** [review]

**Review by thomasdarimont — APPROVED** [review]

**Review by pascal-hofmann — APPROVED** [review]

**Review by alevit33 — APPROVED** [review]

**Review by spirius — APPROVED** [review]

**Review by madddi — APPROVED** [review]

**Review by Xide — APPROVED** [review]

**Review by randomswdev — APPROVED** [review]

**Review by wadahiro — APPROVED** [review]

**Review by cgroschupp — APPROVED** [review]

**Review by gansb — APPROVED** [review]

**Review by ctrox — APPROVED** [review]

**Review by trois-six — APPROVED** [review]

**Review by sanderginn — APPROVED** [review]

**Review by camelpunch — APPROVED** [review]

**Review by whiskeysierra — APPROVED** [review]

**Review by smoehrle — APPROVED** [review]

**Review by naushadh — APPROVED** [review]

**Review by daviddelannoy — APPROVED** [review]

**Review by vhiairrassary — APPROVED** [review]

**Review by pths — APPROVED** [review]

**Review by maximepiton — APPROVED** [review]

**Review by MatrixCrawler — APPROVED** [review]

**Review by hamiltont — APPROVED** [review]
Thanks for all your work on this ❤️

**Review by NataliaKhodiakova — APPROVED** [review]

**Review by wombat — APPROVED** [review]

**Review by dlechevalier — APPROVED** [review]

**Review by yspotts — APPROVED** [review]

**Review by pablo-ruth — APPROVED** [review]

**Review by f-stibane — APPROVED** [review]

**Review by fharding1 — APPROVED** [review]

**Review by 1337andre — APPROVED** [review]

**Review by thyming — APPROVED** [review]

**Review by jkemming — APPROVED** [review]

**Review by nolte — APPROVED** [review]

**Review by dmeyerholt — APPROVED** [review]
thanks @mrparkers for all your work

**Review by rjmasikome — APPROVED** [review]

**Review by hcl31415 — APPROVED** [review]

**Review by malfter — APPROVED** [review]
thanks @mrparkers for all your work

**Review by BernhardBerbuir — APPROVED** [review]

**Review by RomanNess — APPROVED** [review]

**Review by toddkazakov — APPROVED** [review]

**Review by LoicGombeaud — APPROVED** [review]

**Review by PSanetra — APPROVED** [review]

**Review by jermarchand — APPROVED** [review]

**Review by klausenbusk — APPROVED** [review]

**Review by jgrgt — APPROVED** [review]

**Review by Kidsan — APPROVED** [review]

**Review by arminfelder — APPROVED** [review]

**Review by aromeyer — APPROVED** [review]

**Review by lathspell — APPROVED** [review]

**Review by francois-travais — APPROVED** [review]

**Review by dullest — APPROVED** [review]

**Review by bturbes — APPROVED** [review]

**Review by Photonios — APPROVED** [review]

**Review by ChrisHubinger — APPROVED** [review]

**Review by alexashley — APPROVED** [review]

**Review by aroemers — APPROVED** [review]

**Review by awilliamsOM1 — APPROVED** [review]

**Review by rd-robert-avram — APPROVED** [review]

**Comment by sschu** [comment]
Just pinging some people who haven't responded, yet.
@AndrewChubatiuk @Vlad-Kirichenko @StatueFungus @m-v-k @bl00mber @yesteph @Kyos @shellrausch @Zeldhyr @javefang @Floby @dbolack @chanhht @Korsarro69 @sl-benoitoyez @Shubhammathur22 @hcl31415 @paulvollmer @alex-hempel @ltscif @pmellati @jjarman-uk @Paul-Gd @hnnsngl @chifu1234 @SvenHamers @JackHartley @bplotnick-humane @imykolenko @svenhartmann @pstanton237 @xiaoyang-connyun @DOboznyi @Kent1 @elmarx @darin-sai

**Review by Paul-Gd — APPROVED** [review]

**Review by JackHartley — APPROVED** [review]

**Review by hcl31415 — APPROVED** [review]
Fine with me

**Review by Korsarro69 — APPROVED** [review]

**Review by elmarx — APPROVED** [review]

**Review by StatueFungus — APPROVED** [review]

**Review by alex-hempel — APPROVED** [review]

**Review by hnnsngl — APPROVED** [review]

**Review by Kyos — APPROVED** [review]

**Review by Vlad-Kirichenko — APPROVED** [review]

**Review by AndrewChubatiuk — APPROVED** [review]

**Review by javefang — APPROVED** [review]

**Review by yesteph — APPROVED** [review]
LGTM

**Comment by sschu** [comment]
It's quite unbelievable but we got approvals for more than 97% of the code in the provider. A big thanks to everyone for approving! If there is anyone left who is not fine with the license change, please reach out to us and we will find a solution.

Another thanks again to @mrparkers for all the work he put into the provider! 

Michael will transfer the repository soon and then we will start working on the open issues and supporting the current Keycloak versions...

**Comment by dclasen-qd** [comment]
Hey everyone,

I wanted to let you know that my colleagues (@markus-qvest-seidl, @sschum and @headcr4sh) have been working on the open issues and Keycloak version compatibility during the license change took place. https://github.com/qvest-digital/terraform-provider-keycloak

@sschu As you know, we discussed this a few weeks ago via email with @ahus1 and @thomasdarimont. Which is why we wanted to wait with the PR until the repository move is complete, but I've now seen that some of your changes are along the same lines. 

Does it make sense for you that we sync our fork and then send the PR now or shall we continue waiting? 

Best,
Daniel

**Comment by sschu** [comment]
@dclasen-qd Thanks! I would say lets do the first release in the new org and then start working on updating to the current Keycloak versions.

**Pull request merged**
