### PR TITLE
handle both scope and resource permission types

### PR DESCRIPTION
**Pull request by yspotts**
This PR allows for handling all types of permissions - resources as well as scopes

### CODE REVIEW

**Comment by Amad27** [comment]
@mrparkers 
Hey, we updated some tests, and the example. Could you please let us know what you think?

**Comment by rfahsel3** [comment]
Wow! This would be really helpful. Can we get this merged? It looks like the tests have been completed.

**Comment by mrparkers** [comment]
Thanks for adding the tests, @Amad27!

I pulled this down locally and tested the changes you made to `example/main.tf`.  Everything looks good, except that running `terraform apply` and then running a following `terraform destroy` results in a failure.  This appears to only happen on this branch and not on master.  Would you or @yspotts mind taking a look at this?

**Comment by Amad27** [comment]
@mrparkers I just retested it locally and was able to get it to apply and destroy without errors after running the `make user-federation-example` command. Could you please show me what error are you receiving?

**Comment by mrparkers** [comment]
Hmm, I must have had something weird going on with my local setup, because I'm not running into those errors anymore.

I probably just messed something up locally.

**Pull request merged**
