### PR TITLE
add cache policy parameter to ldap user federation

### PR DESCRIPTION
**Pull request by cgroschupp**

### CODE REVIEW

**Comment by mrparkers** [comment]
Hey @cgroschupp, thanks for the PR.  These changes look good.  What would you think about deprecating the existing `cache_policy` attribute in favor of this new schema you've created?  I figure the updated version could look something like this:

```hcl
cache {
  policy          = "EVICT_WEEKLY"
  eviction_day    = 2
  eviction_hour   = 0
  eviction_minute = 0
}
```

If you like this, I can push some changes to your branch to get it implemented, or you could take a stab at it yourself.

**Comment by cgroschupp** [comment]
@mrparkers thank you for your feedback. I have deprecated cache_policy and added it to the cache schema.

**Comment by cgroschupp** [comment]
@mrparkers Is the change ok?

**Review by mrparkers — APPROVED** [review]
Yup this looks good, thanks for the PR!

**Pull request merged**
