### PR TITLE
 SAML Authn IdP Enhancements

### PR DESCRIPTION
**Pull request by dnic**
See https://github.com/mrparkers/terraform-provider-keycloak/pull/476#issue-798748923

### CODE REVIEW

**Comment by dnic** [comment]
Rebased. @mrparkers could you please take a look at these enhancements to SAML? Danke.

**Comment by mrparkers** [comment]
Hi @dnic, sorry for the delay.  I made some fixes to the custom marshaling implementation, so this should work now.  I'll try and get this merged and released soon.

**Comment by mrparkers** [comment]
Thanks for your work on this @dnic!

**Comment by dnic** [comment]
Awesome. Thanks @mrparkers.

**Pull request merged**
