### PR TITLE
Update resource_keycloak_ldap_role_mapper.go

### PR DESCRIPTION
**Pull request by DOboznyi**
Seems as this field was accidentally removed

### CODE REVIEW

**Comment by DOboznyi** [comment]
@mrparkers could you check this change?

**Comment by mrparkers** [comment]
Hey @DOboznyi, maybe I'm missing something here, but it looks like this field was removed from Keycloak.  I tested Keycloak 11, 12, and 13, and none of them have this setting anymore.  That's why I removed it.

Are you using a version of Keycloak that still uses this field?  If so, I can accept this PR and cut a release for you, but I would also want to see the docs updated to specify this as a supported field again.

**Comment by DOboznyi** [comment]
Hey. They have such setting and as i can see from keycloak code it's still present ([Link](https://github.com/keycloak/keycloak/pull/6945))

**Review by mrparkers — APPROVED** [review]
I see, my mistake then.  Thanks for the PR!  I'll get the docs fixed as well.

**Comment by DOboznyi** [comment]
When will be new release with this fix?

**Pull request merged**
