### PR TITLE
Register required action if not reqistered

### LINKED ISSUE #354: Support registering a new required action
https://github.com/mrparkers/terraform-provider-keycloak/pull/131 implemented so we can update existing required action, but we can't add new required actions (ex: WebAuthn).

Registering a new required action is done by posting to [`/{realm}/authentication/register-required-action`](https://www.keycloak.org/docs-api/11.0/rest-api/index.html#_registerrequiredaction), ex:
```sh
$ curl 'http://localhost:8080/auth/admin/realms/master/authentication/register-required-action' -H 'Content-Type: application/json' -H 'Authorization: Bearer eyJhbGc...' --data-raw '{"providerId":"webauthn-register","name":"Webauthn Register"}'
```

Unregistered required actions can be GET from [`unregistered-required-actions`](https://www.keycloak.org/docs-api/11.0/rest-api/index.html#_getunregisteredrequiredactions).

### PR DESCRIPTION
**Pull request by klausenbusk**
Fix #354

### CODE REVIEW

**Comment by klausenbusk** [comment]
I'm not sure the failure is related to the changes?

**Comment by klausenbusk** [comment]
> I'm not sure the failures is related to the changes?

I just rebease with the circleci test timeout from master (https://github.com/mrparkers/terraform-provider-keycloak/commit/000b2485152725eab5ba598bc69947db036d84d3) and now CI is green.

**Comment by mrparkers** [comment]
this looks good, just a couple of thoughts:

- could you add the example action you're using to one of the existing test cases to verify that this will work going forward
- in terms of the lifecycle of a newly registered required action, do you think it should be "unregistered" on delete?  just want to hear your thoughts on this.

**Comment by klausenbusk** [comment]
> could you add the example action you're using to one of the existing test cases to verify that this will work going forward

Sure, will do.

> in terms of the lifecycle of a newly registered required action, do you think it should be "unregistered" on delete? just want to hear your thoughts on this.

You can't "unregister" a required action, you can only delete it (at which point you would need to register it again).

**Review by mrparkers — APPROVED** [review]
thanks for adding that test, LGTM 👍

**Pull request merged**
